CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    companyId BIGINT,
    phone VARCHAR(20)
    CONSTRAINT user_const CHECK (firstName <> '' AND lastName <> '' AND phone <> '')
);